// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_knn_c_euclidean
double my_knn_c_euclidean(NumericVector X, NumericVector X0);
RcppExport SEXP _rcppAssignment_my_knn_c_euclidean(SEXP XSEXP, SEXP X0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    rcpp_result_gen = Rcpp::wrap(my_knn_c_euclidean(X, X0));
    return rcpp_result_gen;
END_RCPP
}
// my_knn_c_task2
int my_knn_c_task2(NumericMatrix X, NumericVector X0, IntegerVector y);
RcppExport SEXP _rcppAssignment_my_knn_c_task2(SEXP XSEXP, SEXP X0SEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(my_knn_c_task2(X, X0, y));
    return rcpp_result_gen;
END_RCPP
}
// my_knn_c_minkowsky
double my_knn_c_minkowsky(NumericVector X, NumericVector X0, double p);
RcppExport SEXP _rcppAssignment_my_knn_c_minkowsky(SEXP XSEXP, SEXP X0SEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(my_knn_c_minkowsky(X, X0, p));
    return rcpp_result_gen;
END_RCPP
}
// my_knn_c_task3
int my_knn_c_task3(NumericMatrix X, NumericVector X0, IntegerVector y, double p);
RcppExport SEXP _rcppAssignment_my_knn_c_task3(SEXP XSEXP, SEXP X0SEXP, SEXP ySEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(my_knn_c_task3(X, X0, y, p));
    return rcpp_result_gen;
END_RCPP
}
// my_knn_c_tuningp
List my_knn_c_tuningp(NumericMatrix X, NumericVector X0, IntegerVector y, NumericVector possible_p);
RcppExport SEXP _rcppAssignment_my_knn_c_tuningp(SEXP XSEXP, SEXP X0SEXP, SEXP ySEXP, SEXP possible_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type possible_p(possible_pSEXP);
    rcpp_result_gen = Rcpp::wrap(my_knn_c_tuningp(X, X0, y, possible_p));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _rcppAssignment_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcppAssignment_my_knn_c_euclidean", (DL_FUNC) &_rcppAssignment_my_knn_c_euclidean, 2},
    {"_rcppAssignment_my_knn_c_task2", (DL_FUNC) &_rcppAssignment_my_knn_c_task2, 3},
    {"_rcppAssignment_my_knn_c_minkowsky", (DL_FUNC) &_rcppAssignment_my_knn_c_minkowsky, 3},
    {"_rcppAssignment_my_knn_c_task3", (DL_FUNC) &_rcppAssignment_my_knn_c_task3, 4},
    {"_rcppAssignment_my_knn_c_tuningp", (DL_FUNC) &_rcppAssignment_my_knn_c_tuningp, 4},
    {"_rcppAssignment_rcpp_hello_world", (DL_FUNC) &_rcppAssignment_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcppAssignment(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
