# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_knn_c_euclidean <- function(X, X0) {
    .Call(`_rcppAssignment_my_knn_c_euclidean`, X, X0)
}

my_knn_c_task2 <- function(X, X0, y) {
    .Call(`_rcppAssignment_my_knn_c_task2`, X, X0, y)
}

my_knn_c_minkowsky <- function(X, X0, p) {
    .Call(`_rcppAssignment_my_knn_c_minkowsky`, X, X0, p)
}

my_knn_c_task3 <- function(X, X0, y, p) {
    .Call(`_rcppAssignment_my_knn_c_task3`, X, X0, y, p)
}

my_knn_c_tuningp <- function(X, X0, y, possible_p) {
    .Call(`_rcppAssignment_my_knn_c_tuningp`, X, X0, y, possible_p)
}

rcpp_hello_world <- function() {
    .Call(`_rcppAssignment_rcpp_hello_world`)
}

